personal:
  name: "Oleksandr Onopchenko"
  title: "Golang Developer"
  email: "a3atlaslife@gmail.com"
  phone: "+380990679259"
  location: "Kyiv, Ukraine"
  linkedin: "https://www.linkedin.com/in/alex-tale"
  github: "https://github.com/fairyTale5571"
  summary: "I am 28 years old and live in Kyiv, Ukraine. I work at PrivatBank, the largest bank in Ukraine, and I'm a tech-lead in one of the leading cryptocurrency communities, A01K. My work is closely related to programming, and I particularly enjoy when my code helps to increase the incomes of clients. I always work in a team and am glad to be part of any community involved in the development of products. In programming, I prefer to use Golang and also work with databases such as MongoDB, MySQL, and PostgreSQL. In my free time, I sometimes focus on developing for open-source projects, allowing me to share knowledge and contribute to the community. I appreciate being part of a professional community where I can grow and help others."
  photo: "https://files.a01k.io/images/2025/1/21/dkio3txkn985.jpeg"

skills:
  - category: "Programming Languages"
    items:
      - name: "Go"
        link: "https://golang.org/"
      - name: "SQL"
        link: "https://www.w3schools.com/sql/"
      - name: "C"
        link: "https://en.wikipedia.org/wiki/C_(programming_language)"
  - category: "Frameworks & Libraries"
    items:
      - name: "Gin"
        link: "https://github.com/gin-gonic/gin"
      - name: "Fiber"
        link: "https://gofiber.io/"
      - name: "Viper"
        link: "https://github.com/spf13/viper"
      - name: "env6"
        link: "https://github.com/caarlos0/env"
      - name: "std sql"
        link: "https://golang.org/pkg/database/sql/"
      - name: "Squirrel"
        link: "https://github.com/Masterminds/squirrel"
      - name: "Gorm"
        link: "https://gorm.io/"
      - name: "Testify"
        link: "https://github.com/stretchr/testify"
      - name: "GoMock"
        link: "https://github.com/golang/mock"
      - name: "Discordgo"
        link: "https://github.com/bwmarrin/discordgo"
      - name: "gotd"
        link: "https://github.com/gotd/td"
      - name: "Telegram bot"
        link: "https://github.com/go-telegram/bot"
      - name: "Minio"
        link: "https://github.com/minio/minio-go"
      - name: "Validator"
        link: "https://github.com/go-playground/validator"
  - category: "Databases"
    items:
      - name: "Postgres"
        link: "https://www.postgresql.org/"
      - name: "MariaDB"
        link: "https://mariadb.org/"
      - name: "MySQL"
        link: "https://www.mysql.com/"
      - name: "SQLite"
        link: "https://www.sqlite.org/"
      - name: "Redis"
        link: "https://redis.io/"
      - name: "MongoDB"
        link: "https://www.mongodb.com/"
  - category: "Tools & Technologies"
    items:
      - name: "Docker"
        link: "https://www.docker.com/"
      - name: "GitHub Actions"
        link: "https://github.com/features/actions"
      - name: "Git"
        link: "https://git-scm.com/"
      - name: "NATS"
        link: "https://nats.io/"
      - name: "AWS S3"
        link: "https://aws.amazon.com/s3/"
      - name: "Grafana"
        link: "https://grafana.com/"
      - name: "Web3"
        link: "https://web3js.readthedocs.io/"
      - name: "CI/CD"
        link: "https://en.wikipedia.org/wiki/CI/CD"
      - name: "Postman"
        link: "https://www.postman.com/"
      - name: "Heroku"
        link: "https://www.heroku.com/"

experience:
  - company: "PrivatBank"
    position: "Software Developer"
    location: "Kyiv, Ukraine"
    employmentType: "Full-time"
    startDate: "Aug 2023"
    endDate: "Present"
    description:
      - "Development and maintenance of Privat24 and Liqpay microservices."
    technologies:
      - name: "Go"
        link: "https://golang.org/"
      - name: "Docker"
        link: "https://www.docker.com/"
      - name: "PostgreSQL"
        link: "https://www.postgresql.org/"
      - name: "Redis"
        link: "https://redis.io/"
      - name: "NATS"
        link: "https://nats.io/"
      - name: "GitHub Actions"
        link: "https://github.com/features/actions"

  - company: "A01K"
    position: "Software Developer"
    location: "Kyiv, Ukraine"
    employmentType: "Part-time"
    startDate: "Mar 2022"
    endDate: "Present"
    description:
      - "Developed and deployed microservices and applications, integrated Telegram and Discord APIs, payment systems, and Web3 technologies."
    technologies:
      - name: "Go"
        link: "https://golang.org/"
      - name: "Docker"
        link: "https://www.docker.com/"
      - name: "PostgreSQL"
        link: "https://www.postgresql.org/"
      - name: "Redis"
        link: "https://redis.io/"
      - name: "Web3"
        link: "https://web3js.readthedocs.io/"
      - name: "Telegram API"
        link: "https://core.telegram.org/bots/api"
      - name: "Discord API"
        link: "https://discord.com/developers/docs/intro"
      - name: "Payment Systems"

  - company: "Soft Group"
    position: "Software Developer"
    location: "Kyiv, Ukraine"
    employmentType: "Part-time"
    startDate: "Oct 2023"
    endDate: "May 2024"
    description:
      - "Developed crypto arbitrage and DEX-CEX solutions using Golang, NATS, Postgres, Redis, and smart contracts with Solidity."
    technologies:
      - name: "Go"
        link: "https://golang.org/"
      - name: "NATS"
        link: "https://nats.io/"
      - name: "Postgres"
        link: "https://www.postgresql.org/"
      - name: "Redis"
        link: "https://redis.io/"
      - name: "Solidity"
        link: "https://soliditylang.org/"

  - company: "Halo Lab"
    position: "Software Developer"
    location: "Odesa, Ukraine"
    employmentType: "Full-time"
    startDate: "Sep 2022"
    endDate: "Jul 2023"
    description:
      - "Developed Golang backend services, integrated third-party services, wrote unit tests, and enhanced functionality for a Health-Care Australian project."
    technologies:
      - name: "Go"
        link: "https://golang.org/"
      - name: "Docker"
        link: "https://www.docker.com/"
      - name: "PostgreSQL"
        link: "https://www.postgresql.org/"
      - name: "Redis"
        link: "https://redis.io/"
      - name: "NATS"
        link: "https://nats.io/"
      - name: "Unit Tests"
        link: "https://golang.org/pkg/testing/"

  - company: "Rocket Life / Rimas RP"
    position: "Game Programmer/CTO"
    location: "Ukraine"
    employmentType: "Full-time"
    startDate: "Mar 2018"
    endDate: "Feb 2022"
    description:
      - "Game design, development of CRM and anti-cheat systems, community management, and monetization strategies."
    technologies:
      - name: "Game Design"
        link: "https://en.wikipedia.org/wiki/Game_design"
      - name: "CRM Development"
        link: "https://en.wikipedia.org/wiki/Customer_relationship_management"
      - name: "Anti-Cheat Systems"
        link: "https://en.wikipedia.org/wiki/Cheating_in_online_games#Anti-cheating_methods"
      - name: "Community Management"
        link: "https://en.wikipedia.org/wiki/Community_management"
      - name: "Monetization Strategies"
        link: "https://en.wikipedia.org/wiki/Monetization"

certifications:
  - "Solidity for Blockchain Development"

languages:
  - language: "English"
    proficiency: "Limited Working"
  - language: "Ukrainian"
    proficiency: "Native"
  - language: "Russian"
    proficiency: "Native"
